package cn.com.dhc.nssol.db.mapper.tableMapper;

import cn.com.dhc.nssol.db.model.TUser;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER
     *
     * @mbggenerated Sat Jul 29 12:24:47 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER
     *
     * @mbggenerated Sat Jul 29 12:24:47 CST 2017
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER
     *
     * @mbggenerated Sat Jul 29 12:24:47 CST 2017
     */
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER
     *
     * @mbggenerated Sat Jul 29 12:24:47 CST 2017
     */
    TUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER
     *
     * @mbggenerated Sat Jul 29 12:24:47 CST 2017
     */
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER
     *
     * @mbggenerated Sat Jul 29 12:24:47 CST 2017
     */
    int updateByPrimaryKey(TUser record);
}