package cn.com.dhc.nssol.db.model;

public class TRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_ROLE.ROLE_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_ROLE.ROLE_CODE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_ROLE.ROLE_NM
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String roleNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_ROLE.ROLE_ID
     *
     * @return the value of PROMNGSYS01.T_ROLE.ROLE_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_ROLE.ROLE_ID
     *
     * @param roleId the value for PROMNGSYS01.T_ROLE.ROLE_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_ROLE.ROLE_CODE
     *
     * @return the value of PROMNGSYS01.T_ROLE.ROLE_CODE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_ROLE.ROLE_CODE
     *
     * @param roleCode the value for PROMNGSYS01.T_ROLE.ROLE_CODE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_ROLE.ROLE_NM
     *
     * @return the value of PROMNGSYS01.T_ROLE.ROLE_NM
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getRoleNm() {
        return roleNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_ROLE.ROLE_NM
     *
     * @param roleNm the value for PROMNGSYS01.T_ROLE.ROLE_NM
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setRoleNm(String roleNm) {
        this.roleNm = roleNm;
    }
}