package cn.com.dhc.nssol.db.model;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.USER_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.USER_CODE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.PASSWORD
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.NAME
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.BIRTH_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.SEXY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String sexy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.PERSON_NUMBER
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String personNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.EMAIL
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.DEL_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String delFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.CANCEL_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String cancelFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.START_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String startDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.END_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String endDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.LOCKED_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String lockedFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.REG_USR_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String regUsrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.REG_DT
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private Date regDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.UPD_USR_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private String updUsrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROMNGSYS01.T_USER.UPD_DT
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    private Date updDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.USER_ID
     *
     * @return the value of PROMNGSYS01.T_USER.USER_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.USER_ID
     *
     * @param userId the value for PROMNGSYS01.T_USER.USER_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.USER_CODE
     *
     * @return the value of PROMNGSYS01.T_USER.USER_CODE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.USER_CODE
     *
     * @param userCode the value for PROMNGSYS01.T_USER.USER_CODE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.PASSWORD
     *
     * @return the value of PROMNGSYS01.T_USER.PASSWORD
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.PASSWORD
     *
     * @param password the value for PROMNGSYS01.T_USER.PASSWORD
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.NAME
     *
     * @return the value of PROMNGSYS01.T_USER.NAME
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.NAME
     *
     * @param name the value for PROMNGSYS01.T_USER.NAME
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.BIRTH_DAY
     *
     * @return the value of PROMNGSYS01.T_USER.BIRTH_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.BIRTH_DAY
     *
     * @param birthDay the value for PROMNGSYS01.T_USER.BIRTH_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.SEXY
     *
     * @return the value of PROMNGSYS01.T_USER.SEXY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getSexy() {
        return sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.SEXY
     *
     * @param sexy the value for PROMNGSYS01.T_USER.SEXY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setSexy(String sexy) {
        this.sexy = sexy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.PERSON_NUMBER
     *
     * @return the value of PROMNGSYS01.T_USER.PERSON_NUMBER
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getPersonNumber() {
        return personNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.PERSON_NUMBER
     *
     * @param personNumber the value for PROMNGSYS01.T_USER.PERSON_NUMBER
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setPersonNumber(String personNumber) {
        this.personNumber = personNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.EMAIL
     *
     * @return the value of PROMNGSYS01.T_USER.EMAIL
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.EMAIL
     *
     * @param email the value for PROMNGSYS01.T_USER.EMAIL
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.DEL_FLG
     *
     * @return the value of PROMNGSYS01.T_USER.DEL_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.DEL_FLG
     *
     * @param delFlg the value for PROMNGSYS01.T_USER.DEL_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.CANCEL_FLG
     *
     * @return the value of PROMNGSYS01.T_USER.CANCEL_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getCancelFlg() {
        return cancelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.CANCEL_FLG
     *
     * @param cancelFlg the value for PROMNGSYS01.T_USER.CANCEL_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setCancelFlg(String cancelFlg) {
        this.cancelFlg = cancelFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.START_DAY
     *
     * @return the value of PROMNGSYS01.T_USER.START_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getStartDay() {
        return startDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.START_DAY
     *
     * @param startDay the value for PROMNGSYS01.T_USER.START_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setStartDay(String startDay) {
        this.startDay = startDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.END_DAY
     *
     * @return the value of PROMNGSYS01.T_USER.END_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getEndDay() {
        return endDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.END_DAY
     *
     * @param endDay the value for PROMNGSYS01.T_USER.END_DAY
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setEndDay(String endDay) {
        this.endDay = endDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.LOCKED_FLG
     *
     * @return the value of PROMNGSYS01.T_USER.LOCKED_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getLockedFlg() {
        return lockedFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.LOCKED_FLG
     *
     * @param lockedFlg the value for PROMNGSYS01.T_USER.LOCKED_FLG
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setLockedFlg(String lockedFlg) {
        this.lockedFlg = lockedFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.REG_USR_ID
     *
     * @return the value of PROMNGSYS01.T_USER.REG_USR_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getRegUsrId() {
        return regUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.REG_USR_ID
     *
     * @param regUsrId the value for PROMNGSYS01.T_USER.REG_USR_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setRegUsrId(String regUsrId) {
        this.regUsrId = regUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.REG_DT
     *
     * @return the value of PROMNGSYS01.T_USER.REG_DT
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.REG_DT
     *
     * @param regDt the value for PROMNGSYS01.T_USER.REG_DT
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.UPD_USR_ID
     *
     * @return the value of PROMNGSYS01.T_USER.UPD_USR_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public String getUpdUsrId() {
        return updUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.UPD_USR_ID
     *
     * @param updUsrId the value for PROMNGSYS01.T_USER.UPD_USR_ID
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setUpdUsrId(String updUsrId) {
        this.updUsrId = updUsrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROMNGSYS01.T_USER.UPD_DT
     *
     * @return the value of PROMNGSYS01.T_USER.UPD_DT
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public Date getUpdDt() {
        return updDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROMNGSYS01.T_USER.UPD_DT
     *
     * @param updDt the value for PROMNGSYS01.T_USER.UPD_DT
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    public void setUpdDt(Date updDt) {
        this.updDt = updDt;
    }
}