package cn.com.dhc.nssol.db.mapper.tableMapper;

import cn.com.dhc.nssol.db.model.TUserRole;
import org.apache.ibatis.annotations.Param;

public interface TUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER_ROLE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("roleId") String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER_ROLE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    int insert(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROMNGSYS01.T_USER_ROLE
     *
     * @mbggenerated Sat Jul 29 17:26:19 CST 2017
     */
    int insertSelective(TUserRole record);
}